version: '3'

services:
  app:
    container_name: marshall_migration_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env.production
    links:
      - database:database
    volumes:
      - ./:/var/www/app/
