version: '3'

services:
  app:
    container_name: marshall_migration_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    depends_on:
      - database
    links:
      - database:database
    volumes:
      - ./:/var/www/app/

  database:
    container_name: marshall_migration_database
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${TARGET_DATABASE_NAME:-marshall}
      - POSTGRES_USER=${TARGET_DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${TARGET_DATABASE_PASSWORD:-postgres}
    ports:
      - ${TARGET_DATABASE_PORT:-5432}:5432
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data:
