version: '3'

services:
  app:
    user: app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    env_file: .env
    depends_on:
      - target-database
      - legacy-database
    links:
      - target-database:database
    volumes:
      - ./:/var/www/app/

  target-database:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${TARGET_DATABASE_NAME:-marshall}
      - POSTGRES_USER=${TARGET_DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${TARGET_DATABASE_PASSWORD:-postgres}
    ports:
      - ${TARGET_DATABASE_PORT:-5432}:5432
    volumes:
      - psql-data:/var/lib/postgresql/data

  legacy-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=${LEGACY_DATABASE_ACCEPT_EULA:-Y}
      - MSSQL_PID=${LEGACY_DATABASE_PID:-Developer}
      - MSSQL_SA_PASSWORD=${LEGACY_DATABASE_SA_PASSWORD:-Strong(!)Password}
    ports:
      - ${LEGACY_DATABASE_SA_PORT:-1433}:1433
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql

volumes:
  psql-data:
  data:
