version: '3'

services:
  app:
    container_name: marshall_migration_production
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env.production
    volumes:
      - ./:/var/www/app/
