def import_tables
  {
    Attribute_Values: attribute_values_columns,
    Attributes: attributes_columns,
    Companies: companies_columns,
    Components: components_columns,
    Entities: entities_columns,
    Folder_Child_Folders: folder_child_folders_columns,
    Folder_Contents: folder_contents_columns,
    Folders: folders_columns,
    Items: items_columns,
    Locations: locations_columns,
    Organizations: organizations_columns,
    Owners: owners_columns,
    Product_Items: product_items_columns,
    Products: products_columns,
    Vault_Entries: vault_entries_columns,
  }
end

def attribute_values_columns
  {
    PK_Id: 'PK_Id',
    Attribute_Id: 'Attribute_Id',
    Object_Id: 'Object_Id',
    Attr_Value: replace_newlines('Attr_Value'),
    Formatted_Value: replace_newlines('Formatted_Value'),
  }
end

def attributes_columns
  {
    Id: 'Id',
    Scope: 'Scope',
    Display_Name: 'Display_Name',
    Description: 'Description',
    Type: 'Type',
    Multi_Value: 'Multi_Value',
    Max_Length: 'Max_Length',
    List_Id: 'List_Id',
    Tag_String: 'Tag_String',
  }
end

def companies_columns
  {
    Id: 'Id',
    Status: 'Status',
    Library_Id: 'Library_Id',
    Display_Name: 'Display_Name',
    Description: 'Description',
    Folder_Id: 'Folder_Id',
    Entity_Collection_Id: 'Entity_Collection_Id',
  }
end

def components_columns
  {
    Id: 'Id',
    Parent_Id: 'Parent_Id',
    Component_Type_Id: 'Component_Type_Id',
    Display_Name: 'Display_Name',
    Description: 'Description',
    File_Id: 'File_Id',
    File_Type: 'File_Type',
    Sequence: 'Sequence',
    Hosted_Access_Information: 'Hosted_Access_Information',
  }
end

def entities_columns
  {
    Id: 'Id',
    Library_Id: 'Library_Id',
    Parent_Entity_Id: 'Parent_Entity_Id',
    Status: 'Status',
    Type_Mask: 'Type_Mask',
    Duplicate_Key: 'Duplicate_Key',
    Login_Name: 'Login_Name',
    Password: 'Password',
    Challenge_Question: 'Challenge_Question',
    Challenge_Answer: 'Challenge_Answer',
    Display_Name: 'Display_Name',
    Prefix: 'Prefix',
    First_Name: 'First_Name',
    Middle_Name: 'Middle_Name',
    Last_Name: 'Last_Name',
    Suffix: 'Suffix',
    Title: replace_newlines('Title'),
    Occupation: 'Occupation',
    Organization_Name: replace_newlines('Organization_Name'),
    Address_Type: 'Address_Type',
    Formatted_Address: replace_newlines('Formatted_Address'),
    Address1: replace_newlines('Address1'),
    Address2: 'Address2',
    City: 'City',
    Region: 'Region',
    Postal_Code: 'Postal_Code',
    Country: 'Country',
    County: 'County',
    County_Code: 'County_Code',
    Carrier_Route: 'Carrier_Route',
    Time_Zone: 'Time_Zone',
    Latitude: 'Latitude',
    Longitude: 'Longitude',
    XAxis: 'XAxis',
    YAxis: 'YAxis',
    ZAxis: 'ZAxis',
    Work_Phone: 'Work_Phone',
    Cell_Phone: 'Cell_Phone',
    Fax: 'Fax',
    Email_Address: 'Email_Address',
    Contact_Preference: 'Contact_Preference',
    Default_Entity_Collection_Id: 'Default_Entity_Collection_Id',
    Payment_Preference: 'Payment_Preference',
    Construction_Codes: 'Construction_Codes',
    Service_Areas: 'Service_Areas',
    Folder_Id: 'Folder_Id',
    Organization_Id: 'Organization_Id',
    Location_Id: 'Location_Id',
    Global_Id: 'Global_Id',
    Last_Edit_DateTime: 'Last_Edit_DateTime',
    Last_Review_DateTime: 'Last_Review_DateTime',
    Enter_DateTime: 'Enter_DateTime',
    Is_Verified: 'Is_Verified',
    Last_Verified_DateTime: 'Last_Verified_DateTime',
    Last_Verify_Request_DateTime: 'Last_Verify_Request_DateTime',
    Next_Verfication_DateTime: 'Next_Verfication_DateTime',
    Is_Listed: 'Is_Listed',
    Is_Searchable: 'Is_Searchable',
    Use_Global_Authentication: 'Use_Global_Authentication',
    Organization_Approval_DateTime: 'Organization_Approval_DateTime',
    Organization_Approval: 'Organization_Approval',
    Active_Email_Address_Id: 'Active_Email_Address_Id',
    Active_Address_Id: 'Active_Address_Id',
    Active_Fax_Phone_Number_Id: 'Active_Fax_Phone_Number_Id',
    Active_Work_Phone_Number_Id: 'Active_Work_Phone_Number_Id',
    Active_Cell_Phone_Number_Id: 'Active_Cell_Phone_Number_Id',
    Is_Contactable: 'Is_Contactable',
    Organization_Function: 'Organization_Function',
    Thumbnail_File_Id: 'Thumbnail_File_Id',
    Is_Prequal_Permitted: 'Is_Prequal_Permitted',
    Is_Email_Address_Syncronized: 'Is_Email_Address_Syncronized',
    Is_Address_Syncronized: 'Is_Address_Syncronized',
    Is_Work_Phone_Syncronized: 'Is_Work_Phone_Syncronized',
    Is_Fax_Phone_Syncronized: 'Is_Fax_Phone_Syncronized',
    Is_Cell_Phone_Syncronized: 'Is_Cell_Phone_Syncronized',
    Default_Organization_Collection_Id: 'Default_Organization_Collection_Id',
    Is_Global_Update_Available: 'Is_Global_Update_Available',
    Is_CSIs_Syncronized: 'Is_CSIs_Syncronized',
    Is_Service_Areas_Syncronized: 'Is_Service_Areas_Syncronized',
    Old_Work_Phone: 'Old_Work_Phone',
    Old_Cell_Phone: 'Old_Cell_Phone',
    Old_Fax: 'Old_Fax',
  }
end

def folder_child_folders_columns
  {
    Parent_Folder_Id: 'Parent_Folder_Id',
    Child_Folder_Id: 'Child_Folder_Id',
    Root_Folder_Id: 'Root_Folder_Id',
    Depth: 'Depth',
    Display_Order: 'Display_Order',
  }
end

def folder_contents_columns
  {
    Folder_Id: 'Folder_Id',
    Object_Id: 'Object_Id',
    Object_Type: 'Object_Type',
    Display_Order: 'Display_Order',
  }
end

def folders_columns
  {
    Id: 'Id',
    Status: 'Status',
    Source_Folder_Id: 'Source_Folder_Id',
    Owner_Id: 'Owner_Id',
    Display_Name: replace_newlines('Display_Name'),
    Description: 'Description',
    Date_Entered: 'Date_Entered',
    Is_Current_Version: 'Is_Current_Version',
    Previous_Version: 'Previous_Version',
    Next_Version: 'Next_Version',
    Create_Date: 'Create_Date',
    Release_Date: 'Release_Date',
    Expire_Date: 'Expire_Date',
    Version_Control_Type: 'Version_Control_Type',
    Content_Change_Style: 'Content_Change_Style',
    Folder_Type: 'Folder_Type',
    Hosted_Access_Information: 'Hosted_Access_Information',
    Item_Search_Id: 'Item_Search_Id',
    Is_Read_Only: 'Is_Read_Only',
    View_Mode: 'View_Mode',
    Mirrored_Folder_Id: 'Mirrored_Folder_Id',
    Default_View_Id: 'Default_View_Id',
  }
end

def items_columns
  {
    Id: 'Id',
    Status: 'Status',
    Under_Change_Status: 'Under_Change_Status',
    Under_Change_Entity_Id: 'Under_Change_Entity_Id',
    Under_Change_Comment: 'Under_Change_Comment',
    Is_Set: 'Is_Set',
    Source_Item_Id: 'Source_Item_Id',
    Item_Type_Id: 'Item_Type_Id',
    Owner_Id: 'Owner_Id',
    Display_Name: replace_newlines('Display_Name'),
    Description: replace_newlines('Description'),
    Enter_Date: 'Enter_Date',
    Last_Edit_DateTime: 'Last_Edit_DateTime',
    Is_Current_Version: 'Is_Current_Version',
    Previous_Version: 'Previous_Version',
    Next_Version: 'Next_Version',
    Total_Formats: 'Total_Formats',
    Total_Excerpts: 'Total_Excerpts',
    Default_Thumbnail_Component_Id: 'Default_Thumbnail_Component_Id',
    Default_Viewable_Format_Id: 'Default_Viewable_Format_Id',
    Is_Default_Viewable_Format_Orderable: 'Is_Default_Viewable_Format_Orderable',
    Default_Printable_Format_Id: 'Default_Printable_Format_Id',
    Is_Default_Printable_Format_Orderable: 'Is_Default_Printable_Format_Orderable',
    Default_Half_Size_Format_Id: 'Default_Half_Size_Format_Id',
    Is_Default_Half_Size_Format_Orderable: 'Is_Default_Half_Size_Format_Orderable',
    Default_Electronic_Format_Id: 'Default_Electronic_Format_Id',
    Is_Default_Electronic_Format_Orderable: 'Is_Default_Electronic_Format_Orderable',
    Default_Design_Format_Id: 'Default_Design_Format_Id',
    Is_Default_Design_Format_Orderable: 'Is_Default_Design_Format_Orderable',
    Default_Markup_Format_Id: 'Default_Markup_Format_Id',
    Default_TakeOff_Format_Id: 'Default_TakeOff_Format_Id',
    Is_Default_TakeOff_Format_Orderable: 'Is_Default_TakeOff_Format_Orderable',
    Default_Format_Info: 'Default_Format_Info',
    Create_Date: 'Create_Date',
    Release_Date: 'Release_Date',
    Expire_Date: 'Expire_Date',
    Sequence: 'Sequence',
    Version_Control_Type: 'Version_Control_Type',
    Orderable: 'Orderable',
    Is_Instant_Printable: 'Is_Instant_Printable',
    Is_Archived: 'Is_Archived',
    Source_Application: 'Source_Application',
    Source_Type: 'Source_Type',
    Template_Id: 'Template_Id',
    Template_Type: 'Template_Type',
    Hosted_Access_Information: 'Hosted_Access_Information',
    Processing_State: 'Processing_State',
    Is_Read_Only: 'Is_Read_Only',
    Small_Tile_Component_Id: 'Small_Tile_Component_Id',
    Large_Tile_Component_Id: 'Large_Tile_Component_Id',
    Default_Offline_Format_Id: 'Default_Offline_Format_Id',
    Is_Attribute_Only: 'Is_Attribute_Only',
    Private_Tile_Component_Id: 'Private_Tile_Component_Id',
  }
end

def locations_columns
  {
    Id: 'Id',
    Parent_Entity_Id: 'Parent_Entity_Id',
    Display_Name: replace_newlines('Display_Name'),
    Trade: 'Trade',
    Address_Type: 'Address_Type',
    Formatted_Address: replace_newlines('Formatted_Address'),
    Address1: 'Address1',
    Address2: 'Address2',
    City: 'City',
    Region: 'Region',
    Postal_Code: 'Postal_Code',
    Country: 'Country',
    County: 'County',
    County_Code: 'County_Code',
    Carrier_Route: 'Carrier_Route',
    Time_Zone: 'Time_Zone',
    Latitude: 'Latitude',
    Longitude: 'Longitude',
    XAxis: 'XAxis',
    YAxis: 'YAxis',
    ZAxis: 'ZAxis',
    Phone: 'Phone',
    Other_Phone: 'Other_Phone',
    Toll_Free_Phone: 'Toll_Free_Phone',
    Fax: 'Fax',
    Email_Address: 'Email_Address',
    Other_Email_Address: 'Other_Email_Address',
    Web_Address: 'Web_Address',
    Construction_Codes: 'Construction_Codes',
    Service_Areas: 'Service_Areas',
    Organization_Id: 'Organization_Id',
    Entity_Id: 'Entity_Id',
    Global_Id: 'Global_Id',
    External_Id: 'External_Id',
    Last_Edit_DateTime: 'Last_Edit_DateTime',
    Last_Review_DateTime: 'Last_Review_DateTime',
  }
end

def organizations_columns
  {
    Id: 'Id',
    Parent_Entity_Id: 'Parent_Entity_Id',
    Display_Name: replace_newlines('Display_Name'),
    Type: 'Type',
    Web_Address: 'Web_Address',
    Domain_Name: 'Domain_Name',
    MBE: 'MBE',
    DBE: 'DBE',
    WBE: 'WBE',
    Union_Shop: 'Union_Shop',
    Bond_Limit: 'Bond_Limit',
    Max_Job_Size: 'Max_Job_Size',
    Location_Id: 'Location_Id',
    Global_Id: 'Global_Id',
    External_Id: 'External_Id',
    Last_Edit_DateTime: 'Last_Edit_DateTime',
    Last_Review_DateTime: 'Last_Review_DateTime',
    Primary_Contact_Entity_Id: 'Primary_Contact_Entity_Id',
    Administrative_Contact_Entity_Id: 'Administrative_Contact_Entity_Id',
    Executive_Contact_Entity_Id: 'Executive_Contact_Entity_Id',
    Finance_Contact_Entity_Id: 'Finance_Contact_Entity_Id',
    Bidding_Contact_Entity_Id: 'Bidding_Contact_Entity_Id',
    Estimating_Contact_Entity_Id: 'Estimating_Contact_Entity_Id',
    Prequal_Contact_Entity_Id: 'Prequal_Contact_Entity_Id',
    Accounting_Contact_Entity_Id: 'Accounting_Contact_Entity_Id',
    Safety_Contact_Entity_Id: 'Safety_Contact_Entity_Id',
    Project_Manager_Contact_Entity_Id: 'Project_Manager_Contact_Entity_Id',
    Warranty_Contact_Entity_Id: 'Warranty_Contact_Entity_Id',
    Remittance_Contact_Entity_Id: 'Remittance_Contact_Entity_Id',
    Status: 'Status',
  }
end

def owners_columns
  {
    Id: 'Id',
    Status: 'Status',
    Company_Id: 'Company_Id',
    Thumbnail_File_Id: 'Thumbnail_File_Id',
    Display_Name: 'Display_Name',
    Description: 'Description',
    Company_Name: 'Company_Name',
    Title: 'Title',
    First_Name: 'First_Name',
    Last_Name: 'Last_Name',
    Work_Phone: 'Work_Phone',
    Home_Phone: 'Home_Phone',
    Fax_Phone: 'Fax_Phone',
    Email_Address: 'Email_Address',
    Address1: 'Address1',
    Address2: 'Address2',
    City: 'City',
    Region: 'Region',
    ZipCode: 'ZipCode',
    Country: 'Country',
    Folder_Id: 'Folder_Id',
    Entity_Collection_Id: 'Entity_Collection_Id',
    Is_Whitelist_Partner: 'Is_Whitelist_Partner',
    Coupon_ID: 'Coupon_ID',
    Coupon_Code_Edit_timestamp: 'Coupon_Code_Edit_timestamp',
    Primary_Association_Owner_ID: 'Primary_Association_Owner_ID',
    Whitelist_Partner_Display_Name: 'Whitelist_Partner_Display_Name',
  }
end

def product_items_columns
  {
    Product_Id: 'Product_Id',
    Item_Id: 'Item_Id',
    Sequence: 'Sequence',
  }
end

def products_columns
  {
    Id: 'Id',
    Status: 'Status',
    Source_Product_Id: 'Source_Product_Id',
    Product_Type_Id: 'Product_Type_Id',
    Display_Name: 'Display_Name',
    Description: replace_newlines('Description'),
    Owner_Id: 'Owner_Id',
    Is_Current_Version: 'Is_Current_Version',
    Previous_Version: 'Previous_Version',
    Next_Version: 'Next_Version',
    Enter_Date: 'Enter_Date',
    Create_Date: 'Create_Date',
    Release_Date: 'Release_Date',
    Expire_Date: 'Expire_Date',
    Thumbnail_File_Id: 'Thumbnail_File_Id',
    Folder_Navigation: 'Folder_Navigation',
    Folder_Id: 'Folder_Id',
    Bid_Packages_Folder_Id: 'Bid_Packages_Folder_Id',
    Version_Control_Type: 'Version_Control_Type',
    Password_Protect: 'Password_Protect',
    Password: 'Password',
    Is_Archived: 'Is_Archived',
    Print_Location_Id: 'Print_Location_Id',
    Entity_Collection_Id: 'Entity_Collection_Id',
    Hosted_Access_Information: 'Hosted_Access_Information',
    Submittals_Folder_Id: 'Submittals_Folder_Id',
    Issues_Folder_Id: 'Issues_Folder_Id',
    Drawings_Folder_Id: 'Drawings_Folder_Id',
    Is_Read_Only: 'Is_Read_Only',
    Design_Drawings_Folder_Id: 'Design_Drawings_Folder_Id',
    Design_Sketches_Folder_Id: 'Design_Sketches_Folder_Id',
    Design_Specifications_Folder_Id: 'Design_Specifications_Folder_Id',
    Field_Drawings_Folder_Id: 'Field_Drawings_Folder_Id',
    Field_Sketches_Folder_Id: 'Field_Sketches_Folder_Id',
    Field_Specifications_Folder_Id: 'Field_Specifications_Folder_Id',
    Is_Basic: 'Is_Basic',
    Basic_Project_Bid_Package_Id: 'Basic_Project_Bid_Package_Id',
    Is_Shared_With_Dodge: 'Is_Shared_With_Dodge',
    Contact_Entity_Id: 'Contact_Entity_Id',
    RFIs_Folder_Id: 'RFIs_Folder_Id',
  }
end

def vault_entries_columns
  {
    Id: 'Id',
    Create_Datetime: 'Create_Datetime',
    Library_Id: 'Library_Id',
    Company_Id: 'Company_Id',
    Owner_Id: 'Owner_Id',
    Vault_Storage_Device_Id: 'Vault_Storage_Device_Id',
    Original_Filename: 'Original_Filename',
    Vault_Directory: 'Vault_Directory',
    Vault_Filename: 'Vault_Filename',
    File_Size: 'File_Size',
    File_Hash: 'File_Hash',
    Last_Access_Datetime: 'Last_Access_Datetime',
    Archive_Volume_Label: 'Archive_Volume_Label',
    File_Type: 'File_Type',
  }
end

def replace_newlines(column)
  "RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(#{column}, CHAR(13), \" \"), CHAR(10), \" \"), CHAR(9), \" \")))"
end
